name: CI - Security Experiment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint_and_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements-dev.txt
      - name: Black check
        run: black --check .
      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: pytest -q tests/unit

  e2e:
    needs: lint_and_unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and start services
        run: |
          docker compose up -d --build
      - name: Show services
        run: docker ps -a
      - name: Wait for services
        run: |
          for i in $(seq 1 60); do
            if curl -sSf http://localhost:8080/auth/health >/dev/null \
              && curl -sSf http://localhost:8080/api/health >/dev/null \
              && curl -sSf http://localhost:8080/alerts/metrics >/dev/null; then
              exit 0
            fi
            sleep 1
          done
          exit 1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements-dev.txt
      - name: Run e2e tests
        env:
          BASE_URL: http://localhost:8080
          PYTHONPATH: .
        run: pytest -q tests/integration
      - name: Logs
        if: always()
        run: docker compose logs --no-color
      - name: Compose down
        if: always()
        run: docker compose down -v
